/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    members: MemberAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    members: Member;
    media: Media;
    posts: Post;
    events: Event;
    'event-registrations': EventRegistration;
    results: Result;
    team: Team;
    sponsors: Sponsor;
    seasons: Season;
    'membership-types': MembershipType;
    memberships: Membership;
    'attribute-definitions': AttributeDefinition;
    'member-attributes': MemberAttribute;
    'size-scales': SizeScale;
    sizes: Size;
    'equipment-items': EquipmentItem;
    'equipment-stock': EquipmentStock;
    'equipment-deliveries': EquipmentDelivery;
    'equipment-packs': EquipmentPack;
    'contact-messages': ContactMessage;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    members: {
      memberships: 'memberships';
      deliveries: 'equipment-deliveries';
      registrations: 'event-registrations';
      raceResults: 'results';
      attributes: 'member-attributes';
    };
    'size-scales': {
      sizes: 'sizes';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'event-registrations': EventRegistrationsSelect<false> | EventRegistrationsSelect<true>;
    results: ResultsSelect<false> | ResultsSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    sponsors: SponsorsSelect<false> | SponsorsSelect<true>;
    seasons: SeasonsSelect<false> | SeasonsSelect<true>;
    'membership-types': MembershipTypesSelect<false> | MembershipTypesSelect<true>;
    memberships: MembershipsSelect<false> | MembershipsSelect<true>;
    'attribute-definitions': AttributeDefinitionsSelect<false> | AttributeDefinitionsSelect<true>;
    'member-attributes': MemberAttributesSelect<false> | MemberAttributesSelect<true>;
    'size-scales': SizeScalesSelect<false> | SizeScalesSelect<true>;
    sizes: SizesSelect<false> | SizesSelect<true>;
    'equipment-items': EquipmentItemsSelect<false> | EquipmentItemsSelect<true>;
    'equipment-stock': EquipmentStockSelect<false> | EquipmentStockSelect<true>;
    'equipment-deliveries': EquipmentDeliveriesSelect<false> | EquipmentDeliveriesSelect<true>;
    'equipment-packs': EquipmentPacksSelect<false> | EquipmentPacksSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | 'es' | 'es'[];
  globals: {
    'home-page': HomePage;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'es';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Member;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface MemberAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  roles: ('admin' | 'editor')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  name: string;
  category?: ('sub18' | 'senior' | 'master' | 'popular') | null;
  federationNumber?: string | null;
  /**
   * Obligatorio para las nuevas altas y el grupo de WhatsApp.
   */
  phone?: string | null;
  /**
   * Condición obligatoria para las nuevas altas. Se registra automáticamente la fecha de aceptación.
   */
  imageRightsAccepted?: boolean | null;
  imageRightsAcceptedAt?: string | null;
  photo?: (number | null) | Media;
  /**
   * Se rellena solo desde la cuota de la temporada actual.
   */
  currentMembershipType?: (number | null) | MembershipType;
  membershipStatus?: ('pending' | 'active' | 'inactive') | null;
  memberships?: {
    docs?: (number | Membership)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  deliveries?: {
    docs?: (number | EquipmentDelivery)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  registrations?: {
    docs?: (number | EventRegistration)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  raceResults?: {
    docs?: (number | Result)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  attributes?: {
    docs?: (number | MemberAttribute)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'members';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-types".
 */
export interface MembershipType {
  id: number;
  /**
   * Ej. Adulto, Infantil, Honorífico
   */
  name: string;
  /**
   * Se genera del título si lo dejas vacío.
   */
  slug?: string | null;
  requiresPayment?: boolean | null;
  /**
   * Cuota de referencia. El cobro se gestiona fuera de la web.
   */
  amount?: number | null;
  period?: ('temporada' | 'anual' | 'mensual') | null;
  /**
   * Equipación, descuentos, inscripciones gratis… (una ventaja por línea).
   */
  includes?: string | null;
  /**
   * Aparece en /hazte-socio para que la gente lo elija.
   */
  showOnWebsite?: boolean | null;
  order?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships".
 */
export interface Membership {
  id: number;
  member: number | Member;
  season: number | Season;
  type?: (number | null) | MembershipType;
  paymentStatus?: ('pending' | 'paid' | 'exempt' | 'cancelled') | null;
  paidAt?: string | null;
  amount?: number | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seasons".
 */
export interface Season {
  id: number;
  /**
   * Ej. 2025/2026
   */
  name: string;
  /**
   * Se genera del título si lo dejas vacío.
   */
  slug?: string | null;
  /**
   * Marca la temporada en curso. Solo una debería estar activa.
   */
  isCurrent?: boolean | null;
  startDate?: string | null;
  endDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Registro de qué se ha entregado a cada socio. El stock se actualiza solo.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipment-deliveries".
 */
export interface EquipmentDelivery {
  id: number;
  member: number | Member;
  season: number | Season;
  item: number | EquipmentItem;
  size?: (number | null) | Size;
  quantity?: number | null;
  status?: ('requested' | 'reserved' | 'delivered' | 'returned') | null;
  payment?: ('included' | 'paid' | 'pending') | null;
  deliveredAt?: string | null;
  label?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Camisetas, pantalones, sudaderas… Añade los artículos que quieras.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipment-items".
 */
export interface EquipmentItem {
  id: number;
  /**
   * Ej. Camiseta oficial, Pantalón corto
   */
  name: string;
  /**
   * Se genera del título si lo dejas vacío.
   */
  slug?: string | null;
  /**
   * Qué tallas admite este artículo.
   */
  sizeScale: number | SizeScale;
  description?: string | null;
  active?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Grupos de tallas. Cada artículo usa una escala (ropa XS-XXL, calzado numérico, única…).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "size-scales".
 */
export interface SizeScale {
  id: number;
  /**
   * Ej. Ropa XS-XXL, Calzado, Talla única
   */
  name: string;
  /**
   * Se genera del título si lo dejas vacío.
   */
  slug?: string | null;
  sizes?: {
    docs?: (number | Size)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sizes".
 */
export interface Size {
  id: number;
  /**
   * Ej. M, 42, Única
   */
  label: string;
  scale: number | SizeScale;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-registrations".
 */
export interface EventRegistration {
  id: number;
  event: number | Event;
  member?: (number | null) | Member;
  category?: ('sub18' | 'senior' | 'master' | 'popular') | null;
  status?: ('pending' | 'confirmed' | 'cancelled') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * Se genera del título si lo dejas vacío.
   */
  slug?: string | null;
  series: 'carrera-principal' | 'social-run' | 'club' | 'carrera-externa';
  date: string;
  location?: string | null;
  image?: (number | null) | Media;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  registrationOpen?: boolean | null;
  /**
   * Déjalo vacío para plazas ilimitadas.
   */
  capacity?: number | null;
  categories?: ('sub18' | 'senior' | 'master' | 'popular')[] | null;
  /**
   * Puedes elegir patrocinadores distintos para cada carrera sin cambiar sus ámbitos generales.
   */
  sponsors?: (number | Sponsor)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors".
 */
export interface Sponsor {
  id: number;
  name: string;
  logo?: (number | null) | Media;
  url?: string | null;
  /**
   * El nivel determina el orden y el tamaño con el que aparece el patrocinador en la web.
   */
  tier: 'principal' | 'oro' | 'plata' | 'bronce' | 'colaborador';
  /**
   * Aparece en toda la web y en el pie de página.
   */
  global?: boolean | null;
  /**
   * Aparece en los espacios generales del club y en la portada.
   */
  clubSponsor?: boolean | null;
  /**
   * Se muestra automáticamente en la próxima carrera principal activa (ALBATERUN).
   */
  mainRaceSponsor?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "results".
 */
export interface Result {
  id: number;
  event: number | Event;
  member?: (number | null) | Member;
  /**
   * Rellénalo aunque enlaces a un socio (para mostrar en público).
   */
  athleteName: string;
  dorsal?: number | null;
  position?: number | null;
  /**
   * Ej. 00:42:15 o 38:20
   */
  mark?: string | null;
  category?: ('sub18' | 'senior' | 'master' | 'popular') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Valores de los campos a medida. Rellena la columna que corresponda al tipo del campo.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-attributes".
 */
export interface MemberAttribute {
  id: number;
  member: number | Member;
  definition: number | AttributeDefinition;
  label?: string | null;
  valueText?: string | null;
  valueLongtext?: string | null;
  valueNumber?: number | null;
  valueDate?: string | null;
  valueBoolean?: boolean | null;
  valueOption?: string | null;
  valueFile?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Define aquí cualquier dato que quieras llevar de cada socio (ropa, salud, permisos…). Aparecerá en la ficha de cada socio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attribute-definitions".
 */
export interface AttributeDefinition {
  id: number;
  /**
   * Ej. Talla de zapatilla, Alergias, Consentimiento de imagen
   */
  label: string;
  /**
   * Se genera del título si lo dejas vacío.
   */
  slug?: string | null;
  type: 'text' | 'longtext' | 'number' | 'date' | 'boolean' | 'select' | 'file';
  /**
   * Valores posibles cuando el tipo es "Lista de opciones".
   */
  options?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Para organizar la ficha: Datos personales, Salud, Administrativo…
   */
  group?: string | null;
  /**
   * Si está marcado, el socio lo ve en su zona privada.
   */
  visibleToMember?: boolean | null;
  /**
   * Si está marcado, el socio puede cambiar su valor.
   */
  editableByMember?: boolean | null;
  required?: boolean | null;
  order?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Se genera del título si lo dejas vacío.
   */
  slug?: string | null;
  cover?: (number | null) | Media;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  status?: ('draft' | 'published') | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  name: string;
  /**
   * Ej. Entrenador, Atleta destacada, Presidente…
   */
  role?: string | null;
  photo?: (number | null) | Media;
  bio?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Cuántas unidades tienes de cada artículo y talla. "Quedan" se calcula solo.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipment-stock".
 */
export interface EquipmentStock {
  id: number;
  item: number | EquipmentItem;
  size: number | Size;
  season: number | Season;
  quantityTotal?: number | null;
  quantityDelivered?: number | null;
  quantityReserved?: number | null;
  /**
   * Compradas − entregadas − reservadas.
   */
  quantityAvailable?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * La equipación que le corresponde a un socio según su tipo y temporada.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipment-packs".
 */
export interface EquipmentPack {
  id: number;
  /**
   * Ej. Pack adulto 2025/2026
   */
  name: string;
  season: number | Season;
  /**
   * Si lo desmarcas, elige a qué tipos de socio aplica.
   */
  appliesToAll?: boolean | null;
  membershipTypes?: (number | MembershipType)[] | null;
  lines?:
    | {
        item: number | EquipmentItem;
        quantity?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: number;
  name: string;
  email: string;
  subject?: ('general' | 'inscripciones' | 'patrocinio' | 'socios') | null;
  message: string;
  handled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'event-registrations';
        value: number | EventRegistration;
      } | null)
    | ({
        relationTo: 'results';
        value: number | Result;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'sponsors';
        value: number | Sponsor;
      } | null)
    | ({
        relationTo: 'seasons';
        value: number | Season;
      } | null)
    | ({
        relationTo: 'membership-types';
        value: number | MembershipType;
      } | null)
    | ({
        relationTo: 'memberships';
        value: number | Membership;
      } | null)
    | ({
        relationTo: 'attribute-definitions';
        value: number | AttributeDefinition;
      } | null)
    | ({
        relationTo: 'member-attributes';
        value: number | MemberAttribute;
      } | null)
    | ({
        relationTo: 'size-scales';
        value: number | SizeScale;
      } | null)
    | ({
        relationTo: 'sizes';
        value: number | Size;
      } | null)
    | ({
        relationTo: 'equipment-items';
        value: number | EquipmentItem;
      } | null)
    | ({
        relationTo: 'equipment-stock';
        value: number | EquipmentStock;
      } | null)
    | ({
        relationTo: 'equipment-deliveries';
        value: number | EquipmentDelivery;
      } | null)
    | ({
        relationTo: 'equipment-packs';
        value: number | EquipmentPack;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: number | ContactMessage;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'members';
        value: number | Member;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'members';
        value: number | Member;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  federationNumber?: T;
  phone?: T;
  imageRightsAccepted?: T;
  imageRightsAcceptedAt?: T;
  photo?: T;
  currentMembershipType?: T;
  membershipStatus?: T;
  memberships?: T;
  deliveries?: T;
  registrations?: T;
  raceResults?: T;
  attributes?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  cover?: T;
  excerpt?: T;
  content?: T;
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  series?: T;
  date?: T;
  location?: T;
  image?: T;
  description?: T;
  registrationOpen?: T;
  capacity?: T;
  categories?: T;
  sponsors?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-registrations_select".
 */
export interface EventRegistrationsSelect<T extends boolean = true> {
  event?: T;
  member?: T;
  category?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "results_select".
 */
export interface ResultsSelect<T extends boolean = true> {
  event?: T;
  member?: T;
  athleteName?: T;
  dorsal?: T;
  position?: T;
  mark?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  photo?: T;
  bio?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors_select".
 */
export interface SponsorsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  url?: T;
  tier?: T;
  global?: T;
  clubSponsor?: T;
  mainRaceSponsor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seasons_select".
 */
export interface SeasonsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  isCurrent?: T;
  startDate?: T;
  endDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-types_select".
 */
export interface MembershipTypesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  requiresPayment?: T;
  amount?: T;
  period?: T;
  includes?: T;
  showOnWebsite?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships_select".
 */
export interface MembershipsSelect<T extends boolean = true> {
  member?: T;
  season?: T;
  type?: T;
  paymentStatus?: T;
  paidAt?: T;
  amount?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attribute-definitions_select".
 */
export interface AttributeDefinitionsSelect<T extends boolean = true> {
  label?: T;
  slug?: T;
  type?: T;
  options?:
    | T
    | {
        label?: T;
        id?: T;
      };
  group?: T;
  visibleToMember?: T;
  editableByMember?: T;
  required?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-attributes_select".
 */
export interface MemberAttributesSelect<T extends boolean = true> {
  member?: T;
  definition?: T;
  label?: T;
  valueText?: T;
  valueLongtext?: T;
  valueNumber?: T;
  valueDate?: T;
  valueBoolean?: T;
  valueOption?: T;
  valueFile?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "size-scales_select".
 */
export interface SizeScalesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  sizes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sizes_select".
 */
export interface SizesSelect<T extends boolean = true> {
  label?: T;
  scale?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipment-items_select".
 */
export interface EquipmentItemsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  sizeScale?: T;
  description?: T;
  active?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipment-stock_select".
 */
export interface EquipmentStockSelect<T extends boolean = true> {
  item?: T;
  size?: T;
  season?: T;
  quantityTotal?: T;
  quantityDelivered?: T;
  quantityReserved?: T;
  quantityAvailable?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipment-deliveries_select".
 */
export interface EquipmentDeliveriesSelect<T extends boolean = true> {
  member?: T;
  season?: T;
  item?: T;
  size?: T;
  quantity?: T;
  status?: T;
  payment?: T;
  deliveredAt?: T;
  label?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipment-packs_select".
 */
export interface EquipmentPacksSelect<T extends boolean = true> {
  name?: T;
  season?: T;
  appliesToAll?: T;
  membershipTypes?: T;
  lines?:
    | T
    | {
        item?: T;
        quantity?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  subject?: T;
  message?: T;
  handled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  /**
   * Línea corta sobre el título. Déjalo vacío para ocultarlo.
   */
  heroEyebrow?: string | null;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  /**
   * Foto que ocupa todo el fondo del hero. Déjalo vacío para un fondo liso.
   */
  heroImage?: (number | null) | Media;
  /**
   * Foto o cartel destacado que se muestra junto al texto. Si la subes, sustituye al logo del club.
   */
  heroForegroundImage?: (number | null) | Media;
  /**
   * Se ignora si has subido una imagen principal.
   */
  heroShowBrandPattern?: boolean | null;
  heroTheme?: ('dark' | 'light') | null;
  /**
   * Capa sobre la foto para que el texto se lea bien.
   */
  heroOverlay?: ('none' | 'subtle' | 'medium' | 'strong') | null;
  heroAlign?: ('left' | 'center' | 'right') | null;
  heroHeight?: ('compact' | 'medium' | 'tall') | null;
  /**
   * Vacío para ocultarlo.
   */
  heroPrimaryLabel?: string | null;
  heroPrimaryHref?: string | null;
  /**
   * Vacío para ocultarlo.
   */
  heroSecondaryLabel?: string | null;
  heroSecondaryHref?: string | null;
  aboutTitle?: string | null;
  aboutBody?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  email?: string | null;
  phone?: string | null;
  address?: string | null;
  instagram?: string | null;
  facebook?: string | null;
  strava?: string | null;
  logoLight?: (number | null) | Media;
  logoDark?: (number | null) | Media;
  brandPrimary?: string | null;
  brandSecondary?: string | null;
  brandAccent?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroEyebrow?: T;
  heroTitle?: T;
  heroSubtitle?: T;
  heroImage?: T;
  heroForegroundImage?: T;
  heroShowBrandPattern?: T;
  heroTheme?: T;
  heroOverlay?: T;
  heroAlign?: T;
  heroHeight?: T;
  heroPrimaryLabel?: T;
  heroPrimaryHref?: T;
  heroSecondaryLabel?: T;
  heroSecondaryHref?: T;
  aboutTitle?: T;
  aboutBody?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  email?: T;
  phone?: T;
  address?: T;
  instagram?: T;
  facebook?: T;
  strava?: T;
  logoLight?: T;
  logoDark?: T;
  brandPrimary?: T;
  brandSecondary?: T;
  brandAccent?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}